url: 'https://github.com/SantoshSatapathy/' # your main domain
baseurl: 'Santosh_Portfolio/' # if you're using custom domain keep this blank example: baseurl: ''

title: Santosh Satapathy
logo: /assets/_DSC0665.jpg
description: text below image
show_downloads: true
theme: jekyll-theme-minimal

# <img src="{{site.baseurl | prepend: site.url}}assets/_DSC0665.png" alt="Untitled" />

