remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# baseur;: 'https://github.com/SantoshSatapathy/' # your main domain
# url: 'Santosh_Portfolio/' # if you're using custom domain keep this blank example: baseurl: ''
# description: SSSSSSSSSSSSSSSSS
# logo: assets/_DSC0665-2 2.png
# description: text below image
show_downloads: false
# theme: jekyll-theme-minimal
# lang        : "en"
# email       : satapats@uoguelph.ca
# date_format : "%-d %b %Y"
